package zsh_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func assetPath(t *testing.T) string {
	t.Helper()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return filepath.Clean(filepath.Join(cwd, "..", "..", "assets", "shell", "zsh", "humansh.zsh"))
}

func TestInteractiveReviewAndRiskProtocol(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	calls := filepath.Join(temp, "calls.log")
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_FAKE_CALLS="$HUMANSH_FAKE_CALLS" HUMANSH_FAKE_UNAVAILABLE="$HUMANSH_FAKE_UNAVAILABLE" zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 600; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    if [[ $seen == ${~pattern} ]]; then
      print -r -- "$seen"
      return 0
    fi
    sleep 0.02
  done
  print -ru2 -- "missing pattern $pattern; received ${(V)seen}"
  return 1
}
wait_slow_calls() {
  local expected=$1 count=0
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    count=$(awk '$0 == "smart|slow please" { found++ } END { print found + 0 }' "$HUMANSH_FAKE_CALLS" 2>/dev/null)
    [[ $count == $expected ]] && return 0
    sleep 0.02
  done
  print -ru2 -- "slow provider call count $count; wanted $expected"
  return 1
}
ready() {
  zpty -w -n H $'\x1d'
  wait_for '*DUMP:<>*' || return 1
  sleep 0.05
}
init='PS1="H> "; KEYTIMEOUT=1; _test_accept() { local captured=$BUFFER; zle -I; print -r -- "ACCEPTED:$captured"; BUFFER=":"; zle accept-line; }; _test_dump() { local enter_binding=$(bindkey -M "$KEYMAP" "^M"); zle -I; print -r -- "DUMP:<$BUFFER>:MAP:$KEYMAP:ENTER:$enter_binding"; zle reset-prompt; }; _test_cursor() { zle -I; print -r -- "CURSOR:$CURSOR:$BUFFER"; zle reset-prompt; }; zle -N _test_accept; zle -N _test_dump; zle -N _test_cursor; for keymap in main emacs viins vicmd; do bindkey -M "$keymap" "^M" _test_accept; bindkey -M "$keymap" "^J" _test_accept; bindkey -M "$keymap" "^]" _test_dump; bindkey -M "$keymap" "^_" _test_cursor; done; source "$HUMANSH_ASSET"; print -r -- READY'
zpty -w H "$init"
wait_for '*READY*' || exit 91
step() {
  print -ru2 -- "STEP:$2"
  zpty -w -n H "$1"
  wait_for "$2" || exit 92
  if [[ $2 == *ACCEPTED:* ]]; then ready || exit 96; fi
  sleep 0.05
}
step $'\r' '*ACCEPTED:*'
step $'git status\r' '*ACCEPTED:git status*'
step $'echo show me the files\r' '*ACCEPTED:echo show me the files*'
step $'which git\r' '*ACCEPTED:which git*'
step $'configured-literal project\r' '*ACCEPTED:configured-literal project*'
step $'configured English prefix files\r' '*Generated by Codex. Review it*'
step $'\x1d' '*DUMP:<print -r -- OVERRIDE_GENERATED>*'
step $'\r' '*ACCEPTED:print -r -- OVERRIDE_GENERATED*'
step $'show me files\r' '*Generated by Codex. Review it*'
step $'\x1d' '*DUMP:<print -r -- GENERATED_LOW>*'
step $'\r' '*ACCEPTED:print -r -- GENERATED_LOW*'
step $'move a file\r' '*changes state*'
step $'\r' '*ACCEPTED:mv old new*'
step $'delete build\r' '*High-risk generated command*'
step $'\r' '*Next: press Ctrl-X then Enter to run it*'
step $'\n' '*Next: press Ctrl-X then Enter to run it*'
step $'\x18\r' '*ACCEPTED:rm -rf build*'
step $'ambiguous words\r' '*Next: press Ctrl-G to translate it, or press Ctrl-X then Enter to run it unchanged*'
step $'\x1d' '*DUMP:<ambiguous words>*'
zpty -w -n H $'\x1b'
sleep 0.2
step $'\x1d' '*DUMP:<>*'
step $'which process is using port 3000\r' '*Not sure whether this is English*'
step $'\x1d' '*DUMP:<which process is using port 3000>*'
zpty -w -n H $'\x15'
step $'open the project folder\r' '*Not sure whether this is English*'
step $'\x1d' '*DUMP:<open the project folder>*'
zpty -w -n H $'\x15'
step $'gti status\r' '*Not sure whether this is English*'
step $'\x1d' '*DUMP:<gti status>*'
zpty -w -n H $'\x15'
step $'ambiguous words\x07' '*Generated by Codex. Review it*'
step $'\x1d' '*DUMP:<print -r -- FORCED>*'
step $'\x18\r' '*ACCEPTED:print -r -- FORCED*'
step $'auth please\r' '*provider login required*'
step $'\x1f' '*CURSOR:11:auth please*'
step $'\x1d' '*DUMP:<auth please>*'
zpty -w -n H $'\x15'
step $'unknown result\r' '*unknown result*'
step $'\x1d' '*DUMP:<unknown result>*'
zpty -w -n H $'\x15'
step $'unsupported please\r' '*cannot be represented as one shell command*'
step $'\x1d' '*DUMP:<unsupported please>*'
zpty -w -n H $'\x15'
step $'incomplete please\r' '*ended before producing a command*'
step $'\x1d' '*DUMP:<incomplete please>*'
zpty -w -n H $'\x15'
step $'policy please\r' '*not safe to place in your terminal*'
step $'\x1d' '*DUMP:<policy please>*'
zpty -w -n H $'\x15'
step $'delete build\r' '*High-risk generated command*'
step $' \r' '*still high risk*'
step $'\x18\r' '*ACCEPTED:rm -rf build *'
step $'delete build\r' '*High-risk generated command*'
zpty -w -n H $'\x1b'
sleep 0.2
step $'\x1d' '*DUMP:<>*'
step $'mv old new\r' '*ACCEPTED:mv old new*'
step $'show me files\r' '*Generated by Codex. Review it*'
zpty -w -n H $'\x15'
step $'rm -rf build\r' '*still high risk*'
step $'\x18\r' '*ACCEPTED:rm -rf build*'
step $'unicode please\r' '*Generated by Codex. Review it*'
step $'\x1f' '*CURSOR:16:print -r -- café*'
step $'\r' '*ACCEPTED:print -r -- café*'
step $'split streams please\r' '*Generated by Codex. Review it*'
step $'\x1d' '*DUMP:<print -r -- SPLIT>*'
step $'\r' '*ACCEPTED:print -r -- SPLIT*'
step $'empty success please\r' '*invalid generated command; your text is unchanged*'
step $'\x1d' '*DUMP:<empty success please>*'
zpty -w -n H $'\x15'
zpty -w -n H $'slow please\r'
wait_for '*Translating with Codex*' || exit 93
wait_for '*Generated by Codex. Review it*' || exit 94
step $'\x18\r' '*ACCEPTED:print -r -- SLOW*'
zpty -w -n H $'slow please\r'
wait_for '*Translating with Codex*' || exit 98
wait_slow_calls 2 || exit 99
zpty -w -n H $'\x03'
sleep 0.1
step $'\x1d' '*DUMP:<slow please>*'
zpty -w -n H $'\x15'
touch "$HUMANSH_FAKE_UNAVAILABLE"
zpty -w -n H $'git status\r'
wait_for '*humansh is unavailable*' || exit 95
ready || exit 97
step $'git status\r' '*ACCEPTED:git status*'
print -r -- ALL_DONE
zpty -d H
`
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "TMPDIR="+temp, "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp, "HUMANSH_FAKE_CALLS="+calls, "HUMANSH_FAKE_UNAVAILABLE="+filepath.Join(temp, "unavailable"))
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zpty protocol: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), "ALL_DONE") {
		t.Fatalf("protocol did not finish:\n%s", output)
	}
	for _, want := range []string{"⠋ Translating with Codex", "⠙ Translating with Codex"} {
		if !strings.Contains(string(output), want) {
			t.Fatalf("animated translation status missing %q:\n%s", want, output)
		}
	}
	callData, err := os.ReadFile(calls)
	if err != nil {
		t.Fatal(err)
	}
	callText := string(callData)
	for _, required := range []string{"smart|git status", "smart|show me files", "translate|ambiguous words", "analyze|rm -rf build", "smart|slow please"} {
		if !strings.Contains(callText, required) {
			t.Errorf("fake call log missing %q:\n%s", required, callText)
		}
	}
	if strings.Contains(callText, "smart|\n") {
		t.Fatalf("empty buffer called the binary:\n%s", callText)
	}
	if leftovers, err := filepath.Glob(filepath.Join(temp, "humansh-zle.*")); err != nil || len(leftovers) != 0 {
		t.Fatalf("private stderr files were not cleaned up: %v err=%v", leftovers, err)
	}
}

func TestInteractiveKeymapsAndCustomBindings(t *testing.T) {
	asset := assetPath(t)
	script := `source "$HUMANSH_ASSET"
print -r -- "LABELS:$_HUMANSH_FORCE_TRANSLATE_LABEL:$_HUMANSH_FORCE_LITERAL_LABEL"
humansh-bindings
for keymap in main emacs viins vicmd; do
  bindkey -M "$keymap" '^M'
  bindkey -M "$keymap" '^J'
  bindkey -M "$keymap" '^U'
  bindkey -M "$keymap" '^X^T'
  bindkey -M "$keymap" '^X^M'
done`
	cmd := exec.Command("zsh", "-f", "-i", "-c", script)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_SMART_ENTER=1", "HUMANSH_CLEAR_LINE_BINDING=^U", "HUMANSH_FORCE_TRANSLATE_BINDING=^X^T", "HUMANSH_FORCE_LITERAL_BINDING=^X^M")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zpty: %v\n%s", err, output)
	}
	text := string(output)
	if strings.Count(text, "_humansh_smart_enter") < 3 {
		t.Fatalf("keymaps not bound:\n%s", text)
	}
	if !strings.Contains(text, "_humansh_force_translate") {
		t.Fatalf("custom force binding missing:\n%s", text)
	}
	if strings.Count(text, "_humansh_force_translate") < 4 || strings.Count(text, "_humansh_force_literal") < 4 {
		t.Fatalf("custom force bindings were not installed in every keymap:\n%s", text)
	}
	if strings.Count(text, "_humansh_clear_line") < 4 {
		t.Fatalf("custom clear-line binding was not installed in every keymap:\n%s", text)
	}
	if !strings.Contains(text, "previous=") || !strings.Contains(text, "force-literal=") {
		t.Fatalf("binding report omitted captured widgets:\n%s", text)
	}
	if !strings.Contains(text, "LABELS:Ctrl-X then Ctrl-T:Ctrl-X then Enter") {
		t.Fatalf("custom bindings were not rendered as actionable key names:\n%s", text)
	}
}

func TestRepeatedEscapeOnlyClearsLiveInputAndHumanshMessage(t *testing.T) {
	asset := assetPath(t)
	script := `zmodload zsh/zpty || exit 90
zpty -b H env HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_SMART_ENTER=0 zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}

zpty -w H 'PS1="E> "; source "$HUMANSH_ASSET"; _test_snapshot() { zle -I; print -r -- "SNAP:<$BUFFER>:MSG:$_HUMANSH_MESSAGE_ACTIVE"; zle reset-prompt; }; _test_message() { _humansh_message "HUMANSH_DESCRIPTION"; }; zle -N _test_snapshot; zle -N _test_message; for keymap in main emacs viins vicmd; do bindkey -M "$keymap" "^]" _test_snapshot; bindkey -M "$keymap" "^\\" _test_message; done; print -r -- READY'
wait_for '*READY*E> *' || exit 91
zpty -w -n H $'draft text\e'
sleep 0.2
zpty -w -n H $'\x1d'
wait_for '*SNAP:<>:MSG:0*' || exit 92
zpty -w -n H $'print -r -- EXECUTED_SENTINEL\r'
wait_for '*EXECUTED_SENTINEL*E> *' || exit 93
zpty -w -n H $'\e'
sleep 0.1
zpty -w -n H $'\e'
sleep 0.1
zpty -w -n H $'\e'
sleep 0.1
zpty -w -n H $'\x1d'
wait_for '*SNAP:<>:MSG:0*' || exit 94
zpty -w -n H $'\x1c'
wait_for '*HUMANSH_DESCRIPTION*' || exit 95
zpty -w -n H $'\e'
sleep 0.2
zpty -w -n H $'\x1d'
wait_for '*SNAP:<>:MSG:0*' || exit 96
print -r -- ESCAPE_DONE
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("repeated Escape behavior: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), "ESCAPE_DONE") {
		t.Fatalf("repeated Escape scenario did not finish:\n%s", output)
	}
}

func TestClearShortcutCancelsActiveTranslationForEveryProvider(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	script := `zmodload zsh/zpty || exit 90
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 60; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
for provider_label in Codex 'Claude Code' 'Cursor CLI' OpenRouter; do
  export HUMANSH_PROVIDER_LABEL=$provider_label
  zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_ASSET="$HUMANSH_ASSET" /bin/zsh -f
  zpty -w H 'PS1="C> "; _cancel_dump() { zle -I; print -r -- "CANCEL_DUMP:<$BUFFER>"; zle reset-prompt; }; zle -N _cancel_dump; bindkey -M emacs "^]" _cancel_dump; source "$HUMANSH_ASSET"; print -r -- CANCEL_READY'
  wait_for '*CANCEL_READY*C> *' || exit 91
  zpty -w -n H $'slow please\x07'
  wait_for "*Translating with ${provider_label}*" || exit 92
  zpty -w -n H $'\x1b'
  sleep 0.2
  zpty -w -n H $'\x1d'
  wait_for '*CANCEL_DUMP:<>*' || exit 93
  print -r -- "CANCELLED:$provider_label"
  zpty -d H
done
print -r -- CANCEL_MATRIX_DONE`
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "TMPDIR="+temp, "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("active Zsh cancellation matrix: %v\n%s", err, output)
	}
	text := string(output)
	for _, label := range []string{"Codex", "Claude Code", "Cursor CLI", "OpenRouter"} {
		if !strings.Contains(text, "CANCELLED:"+label) {
			t.Errorf("provider %q was not cancelled:\n%s", label, text)
		}
	}
	if !strings.Contains(text, "CANCEL_MATRIX_DONE") || strings.Contains(text, "Generated by") {
		t.Fatalf("translation completed instead of being cancelled:\n%s", text)
	}
}

func TestOffCannotBypassPendingHighRiskGate(t *testing.T) {
	asset := assetPath(t)
	script := `source "$HUMANSH_ASSET"
_HUMANSH_PENDING_BUFFER='rm -rf build'
_HUMANSH_PENDING_RISK=14
humansh-off
result_status=$?
print -r -- "STATUS:$result_status ENTER:$(bindkey -M emacs '^M') PENDING:$_HUMANSH_PENDING_RISK"`
	cmd := exec.Command("zsh", "-f", "-i", "-c", script)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zsh: %v\n%s", err, output)
	}
	text := string(output)
	if !strings.Contains(text, "cannot be disabled") || !strings.Contains(text, "STATUS:1") || !strings.Contains(text, "_humansh_smart_enter") || !strings.Contains(text, "PENDING:14") {
		t.Fatalf("humansh-off bypassed high-risk pending state:\n%s", text)
	}
}

func TestSmartEnterDisabledPreservesPriorBinding(t *testing.T) {
	asset := assetPath(t)
	cmd := exec.Command("zsh", "-f", "-i", "-c", `HUMANSH_SMART_ENTER=0; source "$HUMANSH_ASSET"; bindkey -M emacs '^M'; bindkey -M emacs '^J'`)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zsh: %v\n%s", err, output)
	}
	if strings.Contains(string(output), "_humansh_smart_enter") || !strings.Contains(string(output), "accept-line") {
		t.Fatalf("binding changed: %s", output)
	}
}

func TestSmartEnterDisabledTemporarilyGatesGeneratedCommands(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_SMART_ENTER=0 zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
zpty -w H 'PS1="S> "; _disabled_accept() { local captured=$BUFFER; zle -I; print -r -- "DISABLED_ACCEPT:$captured"; BUFFER=":"; zle accept-line; }; zle -N _disabled_accept; for keymap in main emacs viins vicmd; do bindkey -M "$keymap" "^M" _disabled_accept; bindkey -M "$keymap" "^J" _disabled_accept; done; source "$HUMANSH_ASSET"; print -r -- S_READY'
wait_for '*S_READY*S> *' || exit 91
zpty -w -n H $'git status\r'
wait_for '*DISABLED_ACCEPT:git status*' || exit 92
zpty -w -n H $'ambiguous words\x07'
wait_for '*Generated by Codex. Review it*' || exit 93
zpty -w -n H $'\r'
wait_for '*DISABLED_ACCEPT:print -r -- FORCED*' || exit 94
zpty -w -n H $'delete build\x07'
wait_for '*High-risk generated command*' || exit 95
zpty -w -n H $'\r'
wait_for '*Next: press Ctrl-X then Enter to run it*' || exit 96
zpty -w -n H $'\x18\r'
wait_for '*DISABLED_ACCEPT:rm -rf build*' || exit 97
print -r -- DISABLED_DONE
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("smart-enter-disabled gate: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), "DISABLED_DONE") {
		t.Fatalf("disabled gate scenario did not finish:\n%s", output)
	}
}

func TestOffRestoresEachPriorBindingAndReloadIsIdempotent(t *testing.T) {
	asset := assetPath(t)
	script := `_prior_emacs() { zle accept-line; }; _prior_viins() { zle accept-line; }; _prior_vicmd() { zle accept-line; }; _prior_clear() { zle kill-whole-line; }; _prior_translate() { zle send-break; }; _prior_literal() { zle accept-line; }
zle -N _prior_emacs
zle -N _prior_viins
zle -N _prior_vicmd
zle -N _prior_clear
zle -N _prior_translate
zle -N _prior_literal
bindkey -M emacs '^M' _prior_emacs
bindkey -M viins '^M' _prior_viins
bindkey -M vicmd '^M' _prior_vicmd
bindkey -M emacs '^J' _prior_emacs
bindkey -M viins '^J' _prior_viins
bindkey -M vicmd '^J' _prior_vicmd
for keymap in main emacs viins vicmd; do bindkey -M "$keymap" '^[' _prior_clear; bindkey -M "$keymap" '^G' _prior_translate; bindkey -M "$keymap" '^X^M' _prior_literal; done
source "$HUMANSH_ASSET"
source "$HUMANSH_ASSET"
humansh-off
print -r -- "OFF:$(bindkey -M emacs '^M'):$(bindkey -M viins '^M'):$(bindkey -M vicmd '^M')"
print -r -- "OFF-J:$(bindkey -M emacs '^J'):$(bindkey -M viins '^J'):$(bindkey -M vicmd '^J')"
print -r -- "CLEAR-OFF:$(bindkey -M emacs '^['):$(bindkey -M viins '^['):$(bindkey -M vicmd '^[')"
print -r -- "FORCE-OFF:$(bindkey -M emacs '^G'):$(bindkey -M vicmd '^X^M')"
humansh-on
source "$HUMANSH_ASSET"
print -r -- "ON:$(bindkey -M emacs '^M'):$(bindkey -M viins '^M'):$(bindkey -M vicmd '^M')"
humansh-off
print -r -- "OFF2:$(bindkey -M emacs '^M'):$(bindkey -M viins '^M'):$(bindkey -M vicmd '^M')"`
	cmd := exec.Command("zsh", "-f", "-i", "-c", script)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zsh: %v\n%s", err, output)
	}
	text := string(output)
	for _, marker := range []string{
		`OFF:"^M" _prior_emacs:"^M" _prior_viins:"^M" _prior_vicmd`,
		`OFF-J:"^J" _prior_emacs:"^J" _prior_viins:"^J" _prior_vicmd`,
		`CLEAR-OFF:"^[" _prior_clear:"^[" _prior_clear:"^[" _prior_clear`,
		`FORCE-OFF:"^G" _prior_translate:"^X^M" _prior_literal`,
		`ON:"^M" _humansh_smart_enter:"^M" _humansh_smart_enter:"^M" _humansh_smart_enter`,
		`OFF2:"^M" _prior_emacs:"^M" _prior_viins:"^M" _prior_vicmd`,
	} {
		if !strings.Contains(text, marker) {
			t.Errorf("missing %q in:\n%s", marker, text)
		}
	}
}

func TestInvalidEnvironmentBindingDisablesActivation(t *testing.T) {
	asset := assetPath(t)
	cmd := exec.Command("zsh", "-f", "-i", "-c", `HUMANSH_FORCE_TRANSLATE_BINDING='^G;bad'; source "$HUMANSH_ASSET"; bindkey -M emacs '^M'`)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zsh: %v\n%s", err, output)
	}
	text := string(output)
	if !strings.Contains(text, "configured key binding is invalid") || strings.Contains(text, "_humansh_smart_enter") || !strings.Contains(text, "accept-line") {
		t.Fatalf("invalid binding did not fail closed:\n%s", text)
	}
}

func TestPrefixBindingConflictDisablesActivation(t *testing.T) {
	asset := assetPath(t)
	cmd := exec.Command("zsh", "-f", "-i", "-c", `HUMANSH_FORCE_TRANSLATE_BINDING='^X'; HUMANSH_FORCE_LITERAL_BINDING='^X^M'; source "$HUMANSH_ASSET"; bindkey -M emacs '^M'`)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zsh: %v\n%s", err, output)
	}
	text := string(output)
	if !strings.Contains(text, "cannot be prefixes") || strings.Contains(text, "_humansh_smart_enter") || !strings.Contains(text, "accept-line") {
		t.Fatalf("prefix conflict did not fail closed:\n%s", text)
	}
}

func TestClearLinePrefixConflictDisablesActivation(t *testing.T) {
	asset := assetPath(t)
	cmd := exec.Command("zsh", "-f", "-i", "-c", `HUMANSH_FORCE_TRANSLATE_BINDING='^[t'; source "$HUMANSH_ASSET"; bindkey -M emacs '^M'`)
	cmd.Dir = t.TempDir()
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("zsh: %v\n%s", err, output)
	}
	text := string(output)
	if !strings.Contains(text, "cannot be prefixes") || strings.Contains(text, "_humansh_smart_enter") || !strings.Contains(text, "accept-line") {
		t.Fatalf("clear-line prefix conflict did not fail closed:\n%s", text)
	}
}

func TestGeneratedBuiltinsExecuteInParentZsh(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	target := filepath.Join(temp, "target")
	if err := os.Mkdir(target, 0o700); err != nil {
		t.Fatal(err)
	}
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_FAKE_TARGET="$HUMANSH_FAKE_TARGET" zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
zpty -w H 'PS1="P> "; source "$HUMANSH_ASSET"; print -r -- READY'
wait_for '*READY*' || exit 91
zpty -w -n H $'parent cd\r'
wait_for '*changes state*' || exit 92
zpty -w -n H $'\r'
wait_for '*P> *' || exit 93
zpty -w H 'print -r -- "PARENT_PWD:$PWD"'
wait_for "*PARENT_PWD:$HUMANSH_FAKE_TARGET*" || exit 94
zpty -w -n H $'parent export\r'
wait_for '*changes state*' || exit 95
zpty -w -n H $'\r'
wait_for '*P> *' || exit 96
zpty -w H 'print -r -- "PARENT_EXPORT:$HUMANSH_PARENT_EFFECT"'
wait_for '*PARENT_EXPORT:ok*' || exit 97
print -r -- PARENT_DONE
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp, "HUMANSH_FAKE_TARGET="+target)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("parent-shell builtins: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), "PARENT_DONE") {
		t.Fatalf("parent-shell scenario did not finish:\n%s", output)
	}
}

func TestViInsertAndCommandModeEnterCannotBypassSmartWidget(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	calls := filepath.Join(temp, "calls.log")
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_FAKE_CALLS="$HUMANSH_FAKE_CALLS" zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}

wait_calls() {
  local expected=$1 count=0
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    count=$(awk '$0 == "smart|git status" { found++ } END { print found + 0 }' "$HUMANSH_FAKE_CALLS" 2>/dev/null)
    [[ $count == $expected ]] && return 0
    sleep 0.02
  done
  print -ru2 -- "smart call count $count; wanted $expected"
  return 1
}
zpty -w H 'PS1="V> "; KEYTIMEOUT=1; bindkey -v; source "$HUMANSH_ASSET"; _enter_vi_command_mode() { zle vi-cmd-mode; }; _vi_command_ready() { zle -I; print -r -- "VI_COMMAND_READY:KEYMAP=$KEYMAP:CR=$(bindkey -M "$KEYMAP" "^M"):LF=$(bindkey -M "$KEYMAP" "^J")"; zle _humansh_smart_enter; }; zle -N _enter_vi_command_mode; zle -N _vi_command_ready; bindkey -M viins "^]" _enter_vi_command_mode; bindkey -M vicmd "^]" _vi_command_ready; print -r -- V_READY'
wait_for '*V_READY*V> *' || exit 91
zpty -w -n H $'git status\r'
wait_calls 1 || exit 92
wait_for '*V> *' || exit 94
zpty -w -n H $'git status\x1d'
zpty -w -n H $'\x1d'
wait_for '*VI_COMMAND_READY*' || exit 95
wait_calls 2 || exit 93
print -r -- VI_DONE
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp, "HUMANSH_FAKE_CALLS="+calls)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("vi keymaps: %v\n%s", err, output)
	}
	data, err := os.ReadFile(calls)
	if err != nil {
		t.Fatal(err)
	}
	if count := strings.Count(string(data), "smart|git status\n"); count != 2 {
		t.Fatalf("smart calls=%d want 2; log:\n%s\nPTY:\n%s", count, data, output)
	}
}

func TestPriorCustomEnterWidgetRunsInEveryKeymap(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	for _, keymap := range []string{"emacs", "viins", "vicmd"} {
		t.Run(keymap, func(t *testing.T) {
			script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_TEST_KEYMAP="$HUMANSH_TEST_KEYMAP" zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
zpty -w H 'PS1="K> "; if [[ "$HUMANSH_TEST_KEYMAP" == emacs ]]; then bindkey -e; else bindkey -v; fi; _prior_map_accept() { local captured=$BUFFER; zle -I; print -r -- "PRIOR:$KEYMAP:$captured"; BUFFER=":"; zle accept-line; }; _enter_vi_command_mode() { zle vi-cmd-mode; }; zle -N _prior_map_accept; zle -N _enter_vi_command_mode; bindkey -M "$HUMANSH_TEST_KEYMAP" "^M" _prior_map_accept; bindkey -M "$HUMANSH_TEST_KEYMAP" "^J" _prior_map_accept; bindkey -M viins "^Y" _enter_vi_command_mode; source "$HUMANSH_ASSET"; _invoke_smart_for_map() { BUFFER="git status"; CURSOR=${#BUFFER}; zle _humansh_smart_enter; }; zle -N _invoke_smart_for_map; bindkey -M "$HUMANSH_TEST_KEYMAP" "^]" _invoke_smart_for_map; print -r -- MAP_READY'
wait_for '*MAP_READY*K> *' || exit 91
if [[ $HUMANSH_TEST_KEYMAP == vicmd ]]; then
  zpty -w -n H $'\x19'
fi
zpty -w -n H $'\x1d'
expected_keymap=main
[[ $HUMANSH_TEST_KEYMAP == vicmd ]] && expected_keymap=vicmd
wait_for "*PRIOR:$expected_keymap:git status*" || exit 92
zpty -d H`
			ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
			defer cancel()
			cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
			cmd.Dir = temp
			cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp, "HUMANSH_TEST_KEYMAP="+keymap)
			if output, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("custom prior widget: %v\n%s", err, output)
			}
		})
	}
}

func TestCommonZshStartupAndWidgetWrappers(t *testing.T) {
	asset := assetPath(t)
	repo := filepath.Clean(filepath.Join(filepath.Dir(asset), "..", "..", ".."))
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "zsh", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
zpty -w H 'PS1="C> "; plugins=(git zsh-autosuggestions); bindkey -e; typeset -gi _COMPAT_AUTOSUGGEST=0 _COMPAT_HIGHLIGHT=0; _omz_accept_line() { local captured=$BUFFER; zle -I; print -r -- "OMZ_ACCEPT:$captured:WRAPPERS:$_COMPAT_AUTOSUGGEST:$_COMPAT_HIGHLIGHT"; BUFFER=":"; zle accept-line; }; zle -N _omz_accept_line; bindkey -M emacs "^M" _omz_accept_line; bindkey -M emacs "^J" _omz_accept_line; source "$HUMANSH_ASSET"; zle -A _humansh_smart_enter _zsh_autosuggest_orig_humansh; _zsh_autosuggest_wrapper() { (( _COMPAT_AUTOSUGGEST++ )); zle _zsh_autosuggest_orig_humansh; }; zle -N _humansh_smart_enter _zsh_autosuggest_wrapper; zle -A _humansh_smart_enter _zsh_highlight_orig_humansh; _zsh_highlight_wrapper() { (( _COMPAT_HIGHLIGHT++ )); zle _zsh_highlight_orig_humansh; }; zle -N _humansh_smart_enter _zsh_highlight_wrapper; print -r -- COMPAT_READY'
wait_for '*COMPAT_READY*C> *' || exit 91
zpty -w -n H $'git status\r'
wait_for '*OMZ_ACCEPT:git status:WRAPPERS:1:1*' || exit 92
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("common Zsh wrapper compatibility: %v\n%s", err, output)
	}
}

// TestSourcingTheAssetSpawnsNoSubprocess pins the shell-startup cost of the
// integration at zero processes. Resolving anything by running humansh while
// .zshrc is being sourced puts an untimed blocking subprocess in front of every
// interactive shell, so a stalled home directory would hang every new terminal.
// Values the integration needs at load time come from the managed block instead.
//
// The probe below stands in for humansh rather than the shared fake backend: it
// records every invocation before doing anything else and never reads stdin, so
// it cannot miss a call or block on a terminal the way a stdin-reading fake can.
func TestSourcingTheAssetSpawnsNoSubprocess(t *testing.T) {
	asset := assetPath(t)
	temp := t.TempDir()
	calls := filepath.Join(temp, "calls.log")
	probe := "#!/bin/sh\nprintf '%s\\n' \"$*\" >> " + calls + "\nexit 0\n"
	if err := os.WriteFile(filepath.Join(temp, "humansh"), []byte(probe), 0o700); err != nil {
		t.Fatal(err)
	}
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" zsh -f
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
zpty -w H 'PS1="Q> "; source "$HUMANSH_ASSET"; print -r -- SOURCED'
wait_for '*SOURCED*Q> *' || exit 91
print -r -- QUIET_DONE
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("quiet-startup scenario: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), "SOURCED") {
		t.Fatalf("asset did not finish sourcing:\n%s", output)
	}
	if data, readErr := os.ReadFile(calls); readErr == nil && len(strings.TrimSpace(string(data))) != 0 {
		t.Fatalf("sourcing the asset invoked humansh; it must stay process-free at startup. Invocations:\n%s", data)
	}
}
