package e2e_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const (
	e2eRequest = "list all the files in this directory"
	e2eCommand = "ls -la"
)

func TestInstalledZshTranslatesNaturalLanguage(t *testing.T) {
	if os.Getenv("HUMANSH_RUN_E2E") != "1" {
		t.Skip("set HUMANSH_RUN_E2E=1 to run the installed-flow test")
	}
	for _, command := range []string{"go", "sh", "zsh"} {
		if _, err := exec.LookPath(command); err != nil {
			t.Fatalf("required E2E command %q is unavailable: %v", command, err)
		}
	}

	repo := repositoryRoot(t)
	testRoot := t.TempDir()
	home := filepath.Join(testRoot, "home")
	providerBin := filepath.Join(testRoot, "provider-bin")
	if err := os.MkdirAll(home, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(providerBin, 0o700); err != nil {
		t.Fatal(err)
	}

	fakeCodex := filepath.Join(providerBin, "codex")
	buildFixture := exec.Command("go", "build", "-trimpath", "-o", fakeCodex, "./tests/e2e/testdata/fakecodex")
	buildFixture.Dir = repo
	if output, err := buildFixture.CombinedOutput(); err != nil {
		t.Fatalf("build deterministic Codex fixture: %v\n%s", err, output)
	}

	env := isolatedEnvironment(t, home, providerBin)
	installer := exec.Command("sh", filepath.Join(repo, "scripts", "install.sh"), "--local", "--shell", "zsh")
	installer.Dir = repo
	installer.Env = env
	installerOutput, err := installer.CombinedOutput()
	if err != nil {
		t.Fatalf("install checked-out Humansh: %v\n%s", err, installerOutput)
	}
	if text := string(installerOutput); !strings.Contains(text, "Installed humansh to ") || !strings.Contains(text, "setup --shell zsh") {
		t.Fatalf("installer did not complete the normal non-interactive flow:\n%s", text)
	}

	installedBinary := filepath.Join(home, ".local", "bin", "humansh")
	if info, err := os.Stat(installedBinary); err != nil || info.Mode().Perm()&0o111 == 0 {
		t.Fatalf("installed binary is unavailable or not executable: info=%v err=%v", info, err)
	}

	setup := exec.Command(installedBinary, "setup", "--yes", "--provider", "codex", "--shell", "zsh")
	setup.Env = env
	setup.Stdin = strings.NewReader("")
	setupOutput, err := setup.CombinedOutput()
	if err != nil {
		t.Fatalf("complete installed Zsh setup: %v\n%s", err, setupOutput)
	}
	if !strings.Contains(string(setupOutput), "humansh setup complete") {
		t.Fatalf("setup did not report completion:\n%s", setupOutput)
	}

	zshrc := filepath.Join(home, ".zshrc")
	appendZLEProbe(t, zshrc)
	runInteractiveTranslation(t, testRoot, home, env)
}

func appendZLEProbe(t *testing.T, zshrc string) {
	t.Helper()
	file, err := os.OpenFile(zshrc, os.O_WRONLY|os.O_APPEND, 0)
	if err != nil {
		t.Fatalf("open installed .zshrc: %v", err)
	}
	const probe = `
# Test-only observation widget. The installed Humansh block above remains the
# code under test; this widget only exposes the editable ZLE buffer to the
# parent test without accepting or executing it.
bindkey -e
_humansh_e2e_dump_buffer() {
  zle -I
  print -r -- "HUMANSH_E2E_BUFFER:<${BUFFER}>"
  zle reset-prompt
}
zle -N _humansh_e2e_dump_buffer
bindkey -M emacs '^]' _humansh_e2e_dump_buffer
print -r -- "HUMANSH_E2E_READY:$(bindkey -M emacs '^M')"
`
	if _, err := file.WriteString(probe); err != nil {
		_ = file.Close()
		t.Fatalf("append ZLE observation widget: %v", err)
	}
	if err := file.Close(); err != nil {
		t.Fatalf("close installed .zshrc: %v", err)
	}
}

func runInteractiveTranslation(t *testing.T, testRoot, home string, env []string) {
	t.Helper()
	const script = `zmodload zsh/zpty || exit 90
zpty -b H env TERM=xterm-256color HOME="$HUMANSH_E2E_HOME" ZDOTDIR="$HUMANSH_E2E_HOME" PATH="$HUMANSH_E2E_PATH" zsh -d -i
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 1500; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    if [[ $seen == *$pattern* ]]; then
      print -r -- "$seen"
      return 0
    fi
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
wait_for 'HUMANSH_E2E_READY:' || exit 91
zpty -w -n H "$HUMANSH_E2E_REQUEST"$'\r'
wait_for 'Generated by Codex. Review it' || exit 92
zpty -w -n H $'\x1d'
wait_for "HUMANSH_E2E_BUFFER:<${HUMANSH_E2E_COMMAND}>" || exit 93
print -r -- HUMANSH_E2E_DONE
zpty -d H
`

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	command := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	command.Dir = testRoot
	command.Env = setEnvironment(env,
		"HUMANSH_E2E_HOME", home,
		"HUMANSH_E2E_PATH", environmentValue(env, "PATH"),
		"HUMANSH_E2E_REQUEST", e2eRequest,
		"HUMANSH_E2E_COMMAND", e2eCommand,
	)
	output, err := command.CombinedOutput()
	if err != nil {
		if ctx.Err() != nil {
			t.Fatalf("installed Zsh translation exceeded its timeout:\n%s", output)
		}
		t.Fatalf("installed Zsh translation failed: %v\n%s", err, output)
	}
	text := string(output)
	for _, want := range []string{
		"HUMANSH_E2E_READY:",
		"_humansh_smart_enter",
		"Generated by Codex. Review it",
		"HUMANSH_E2E_BUFFER:<" + e2eCommand + ">",
		"HUMANSH_E2E_DONE",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("interactive installed flow did not produce %q:\n%s", want, text)
		}
	}
}

func isolatedEnvironment(t *testing.T, home, providerBin string) []string {
	t.Helper()
	goEnvironmentCommand := exec.Command("go", "env", "GOCACHE", "GOMODCACHE", "GOPATH")
	output, err := goEnvironmentCommand.Output()
	if err != nil {
		t.Fatalf("read configured Go build paths: %v", err)
	}
	goPaths := strings.Split(strings.TrimSpace(string(output)), "\n")
	if len(goPaths) != 3 {
		t.Fatalf("go env returned %d build paths, want 3: %q", len(goPaths), output)
	}
	return setEnvironment(os.Environ(),
		"HOME", home,
		"ZDOTDIR", home,
		"XDG_CONFIG_HOME", filepath.Join(home, "config"),
		"XDG_DATA_HOME", filepath.Join(home, "data"),
		"XDG_CACHE_HOME", filepath.Join(home, "cache"),
		"CODEX_HOME", filepath.Join(home, "codex"),
		"HUMANSH_NONINTERACTIVE", "1",
		"OPENROUTER_API_KEY", "",
		"TERM", "xterm-256color",
		"PATH", providerBin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"GOCACHE", goPaths[0],
		"GOMODCACHE", goPaths[1],
		"GOPATH", goPaths[2],
	)
}

func setEnvironment(environment []string, pairs ...string) []string {
	values := make(map[string]string, len(pairs)/2)
	order := make([]string, 0, len(pairs)/2)
	for index := 0; index < len(pairs); index += 2 {
		values[pairs[index]] = pairs[index+1]
		order = append(order, pairs[index])
	}
	out := make([]string, 0, len(environment)+len(order))
	for _, item := range environment {
		key, _, ok := strings.Cut(item, "=")
		if _, replace := values[key]; !ok || replace {
			continue
		}
		out = append(out, item)
	}
	for _, key := range order {
		out = append(out, key+"="+values[key])
	}
	return out
}

func environmentValue(environment []string, key string) string {
	prefix := key + "="
	for _, item := range environment {
		if strings.HasPrefix(item, prefix) {
			return strings.TrimPrefix(item, prefix)
		}
	}
	return ""
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return filepath.Clean(filepath.Join(workingDirectory, "..", ".."))
}
