package bash_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func repositoryRoot(t *testing.T) string {
	t.Helper()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return filepath.Clean(filepath.Join(cwd, "..", ".."))
}

func modernBash(t *testing.T) string {
	t.Helper()
	var candidates []string
	if configured := os.Getenv("HUMANSH_TEST_BASH"); configured != "" {
		candidates = append(candidates, configured)
	}
	candidates = append(candidates, "/opt/homebrew/bin/bash", "/usr/local/bin/bash")
	if path, err := exec.LookPath("bash"); err == nil {
		candidates = append(candidates, path)
	}
	seen := map[string]bool{}
	for _, candidate := range candidates {
		if seen[candidate] {
			continue
		}
		seen[candidate] = true
		if err := exec.Command(candidate, "--noprofile", "--norc", "-c", `(( BASH_VERSINFO[0] > 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 3) ))`).Run(); err == nil {
			return candidate
		}
	}
	t.Skip("Bash 4.3+ is not installed; older Bash cannot safely capture and restore all Readline bindings")
	return ""
}

func TestInteractiveExplicitTranslationAndRiskGate(t *testing.T) {
	bashPath := modernBash(t)
	repo := repositoryRoot(t)
	asset := filepath.Join(repo, "assets", "shell", "bash", "humansh.bash")
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "bash", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	calls := filepath.Join(temp, "calls.log")
	script := `zmodload zsh/zpty || exit 90
zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" TERM=xterm-256color HUMANSH_PROVIDER_LABEL=Codex HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_FAKE_CALLS="$HUMANSH_FAKE_CALLS" HUMANSH_SMART_ENTER=0 "$HUMANSH_BASH" --noprofile --norc -i
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 600; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
zpty -w H 'PS1="B> "; set +o history; _test_dump() { printf "\nDUMP:<%s>:POINT:%s\n" "$READLINE_LINE" "$READLINE_POINT"; }; bind -x '"'"'"\C-]":_test_dump'"'"'; source "$HUMANSH_ASSET"; source "$HUMANSH_ASSET"; printf "READY\n"'
wait_for '*READY*B> *' || exit 91
step() {
  zpty -w -n H "$1"
  wait_for "$2" || exit 92
  sleep 0.05
}
step $'printf "NORMAL_OK\\n"\r' '*NORMAL_OK*B> *'
step $'show me files\x07' '*Generated by Codex. Review it*'
step $'\x1d' '*DUMP:<printf '\''%s\\n'\'' BASH_GENERATED_LOW>*'
step $'\r' '*BASH_GENERATED_LOW*B> *'
zpty -w -n H $'slow please\x07'
wait_for '*⠋ Translating with Codex*' || exit 93
wait_for '*⠙ Translating with Codex*' || exit 94
wait_for '*Generated by Codex. Review it*' || exit 95
step $'\x1d' '*DUMP:<printf '\''%s\\n'\'' BASH_SLOW>*'
step $'\r' '*BASH_SLOW*B> *'
zpty -w -n H $'uncleared\x1b'
sleep 0.8
step $'\x1d' '*DUMP:<>*'
step $'delete build\x07' '*High-risk generated command*'
step $'\r' '*Next: press Ctrl-X then Enter to run it*'
step $'\x1d' '*DUMP:<printf '\''%s\\n'\'' BASH_GENERATED_HIGH>*'
step $'\x18\r' '*BASH_GENERATED_HIGH*B> *'
print -r -- BASH_DONE
zpty -d H`
	ctx, cancel := context.WithTimeout(context.Background(), 35*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "TMPDIR="+temp, "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp, "HUMANSH_FAKE_CALLS="+calls, "HUMANSH_BASH="+bashPath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("Bash Readline PTY: %v\n%s", err, output)
	}
	if !strings.Contains(string(output), "BASH_DONE") {
		t.Fatalf("Bash scenario did not finish:\n%s", output)
	}
	if count := strings.Count(string(output), "humansh active in Bash"); count != 1 {
		t.Fatalf("Bash activation guidance appeared %d times, want once:\n%s", count, output)
	}
	callData, err := os.ReadFile(calls)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"translate|show me files", "translate|slow please", "translate|delete build"} {
		if !strings.Contains(string(callData), want) {
			t.Errorf("fake call log missing %q:\n%s", want, callData)
		}
	}
	if lines := strings.Count(strings.TrimSpace(string(callData)), "\n") + 1; lines != 3 {
		t.Fatalf("Bash startup or ordinary Enter invoked humansh; calls=%d\n%s", lines, callData)
	}
}

func TestRedirectedTranslationStatusIsStableText(t *testing.T) {
	bashPath := modernBash(t)
	repo := repositoryRoot(t)
	asset := filepath.Join(repo, "assets", "shell", "bash", "humansh.bash")
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "bash", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}

	command := exec.Command(bashPath, "--noprofile", "--norc", "-i", "-c", `source "$HUMANSH_ASSET"; READLINE_LINE='show me files'; READLINE_POINT=${#READLINE_LINE}; _humansh_call; printf 'RESULT:<%s>\n' "$READLINE_LINE"`)
	command.Dir = temp
	command.Env = append(os.Environ(), "PATH="+temp+string(os.PathListSeparator)+os.Getenv("PATH"), "HUMANSH_ASSET="+asset, "HUMANSH_PROVIDER_LABEL=Codex", "HUMANSH_SMART_ENTER=0", "TERM=dumb")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("redirected Bash translation: %v\n%s", err, output)
	}
	text := string(output)
	if !strings.Contains(text, "… Translating with Codex…") || !strings.Contains(text, "RESULT:<printf '%s\\n' BASH_GENERATED_LOW>") {
		t.Fatalf("redirected translation status/result missing:\n%s", text)
	}
	if strings.Contains(text, "\r") {
		t.Fatalf("redirected translation status contained animation controls: %q", text)
	}
	if strings.Contains(text, "humansh active in Bash") {
		t.Fatalf("redirected Bash session received an activation notice: %q", text)
	}
}

func TestClearShortcutCancelsActiveTranslationForEveryProvider(t *testing.T) {
	bashPath := modernBash(t)
	repo := repositoryRoot(t)
	asset := filepath.Join(repo, "assets", "shell", "bash", "humansh.bash")
	temp := t.TempDir()
	fake := filepath.Join(temp, "humansh")
	build := exec.Command("go", "build", "-o", fake, filepath.Join(repo, "tests", "bash", "testdata", "fakehumansh.go"))
	build.Dir = repo
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build fake backend: %v\n%s", err, output)
	}
	script := `zmodload zsh/zpty || exit 90
wait_for() {
  local pattern=$1 chunk seen=''
  local -i attempt
  for (( attempt = 1; attempt <= 60; attempt++ )); do
    while zpty -r -t H chunk; do seen+=$chunk; done
    [[ $seen == ${~pattern} ]] && { print -r -- "$seen"; return 0; }
    sleep 0.02
  done
  print -ru2 -- "missing $pattern; received ${(V)seen}"
  return 1
}
for provider_label in Codex 'Claude Code' 'Cursor CLI' OpenRouter; do
  export HUMANSH_PROVIDER_LABEL=$provider_label
  zpty -b H env PATH="$HUMANSH_FAKE_DIR:$PATH" HUMANSH_ASSET="$HUMANSH_ASSET" HUMANSH_SMART_ENTER=0 "$HUMANSH_BASH" --noprofile --norc -i
  zpty -w H 'PS1="C> "; set +o history; _cancel_dump() { printf "\nCANCEL_DUMP:<%s>\n" "$READLINE_LINE"; }; bind -x '"'"'"\C-]":_cancel_dump'"'"'; source "$HUMANSH_ASSET"; printf "CANCEL_READY\n"'
  wait_for '*CANCEL_READY*C> *' || exit 91
  zpty -w -n H $'slow please\x07'
  wait_for "*Translating with ${provider_label}*" || exit 92
  zpty -w -n H $'\x1b'
  wait_for '*                                    *' || exit 93
  sleep 0.05
  zpty -w -n H $'\x1d'
  wait_for '*CANCEL_DUMP:<>*' || exit 94
  print -r -- "CANCELLED:$provider_label"
  zpty -d H
done
print -r -- CANCEL_MATRIX_DONE`
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "zsh", "-f", "-c", script)
	cmd.Dir = temp
	cmd.Env = append(os.Environ(), "TMPDIR="+temp, "HUMANSH_ASSET="+asset, "HUMANSH_FAKE_DIR="+temp, "HUMANSH_BASH="+bashPath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("active Bash cancellation matrix: %v\n%s", err, output)
	}
	text := string(output)
	for _, label := range []string{"Codex", "Claude Code", "Cursor CLI", "OpenRouter"} {
		if !strings.Contains(text, "CANCELLED:"+label) {
			t.Errorf("provider %q was not cancelled:\n%s", label, text)
		}
	}
	if !strings.Contains(text, "CANCEL_MATRIX_DONE") || strings.Contains(text, "Generated by") {
		t.Fatalf("translation completed instead of being cancelled:\n%s", text)
	}
}

func TestOffCannotBypassPendingHighRiskGate(t *testing.T) {
	bashPath := modernBash(t)
	asset := filepath.Join(repositoryRoot(t), "assets", "shell", "bash", "humansh.bash")
	script := `source "$HUMANSH_ASSET"; _HUMANSH_PENDING_BUFFER="printf blocked"; _HUMANSH_PENDING_RISK=14; _humansh_enable_pending_gate; humansh-off; status=$?; printf 'STATUS:%s:GATED:%s:ACTIVE:%s\n' "$status" "$_HUMANSH_ENTER_GATED" "$_HUMANSH_ACTIVE"`
	cmd := exec.Command(bashPath, "--noprofile", "--norc", "-i", "-c", script)
	cmd.Env = append(os.Environ(), "HUMANSH_ASSET="+asset, "HUMANSH_SMART_ENTER=0")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("Bash high-risk off check: %v\n%s", err, output)
	}
	text := string(output)
	if !strings.Contains(text, "cannot be disabled") || !strings.Contains(text, "STATUS:1:GATED:1:ACTIVE:1") {
		t.Fatalf("humansh-off bypassed the Bash risk gate:\n%s", text)
	}
}

func TestAppleBashThreeDisablesAssetActionably(t *testing.T) {
	if _, err := os.Stat("/bin/bash"); err != nil {
		t.Skip("no system Bash")
	}
	asset := filepath.Join(repositoryRoot(t), "assets", "shell", "bash", "humansh.bash")
	command := exec.Command("/bin/bash", "--noprofile", "--norc", "-i", "-c", `source "$HUMANSH_ASSET"`)
	command.Env = append(os.Environ(), "HUMANSH_ASSET="+asset)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("source with system Bash: %v\n%s", err, output)
	}
	versionOutput, _ := exec.Command("/bin/bash", "--version").Output()
	if !strings.Contains(string(versionOutput), "version 3.") {
		t.Skip("system Bash is modern on this platform")
	}
	if !strings.Contains(string(output), "Bash 4.3 or newer is required") {
		t.Fatalf("Bash 3 did not fail actionably:\n%s", output)
	}
}
